### ISSUE TITLE
Missing file/ module (calc_wrf_severe) for SkewT 

### ISSUE THREAD

**Issue by wxguy** [lmadaus/old_wrf_plotting_scripts#4]
I have modified your script to plot few variables and it absolutely works fine here. Now I want to plot SkewT diagram for a few selected stations. The 'plot_wrf_skewt.py' file was able to extract the values for a particular coordinates. However it resulted in error without plotting as there exist no 'calc_wrf_severe' module. 

I request you to add those missing files to make it complete package.

**Comment by lmadaus** [comment]
Unfortunately there never was a working calc_wrf_severe.py script. I suggest you check out the SHARPpy package for a much better and more up-to-date way to calculate sounding parameters. 

https://github.com/sharppy/SHARPpy

I appreciate your interest in this code, but am no longer actively supporting it.

**Comment by wxguy** [comment]
Thanks for the clarification. I will check out the SHARPpy project.
